apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
  labels:
    app: frontend-app

spec:
  ports:
    - port: 3000
      protocol: TCP
      name: nodejs-server
      targetPort: 3000
  selector:
    app: frontend-app
    tier: backend
  type: ClusterIP