apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
  labels:
    app: backend-app

spec:
  ports:
    - port: 8000
      protocol: TCP
      name: nodejs-server
      targetPort: 8000
  selector:
    app: backend-app
    tier: backend
  type: ClusterIP