name: backend pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd ./Backend
          npm install

      - name: Build the project
        run: |
          cd ./Backend
          npm run build
        env:
          NODE_ENV: production

      - name: Archive node_modules
        uses: actions/upload-artifact@v2
        with:
          name: node_modules
          path: ./Backend/node_modules

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Download node_modules
        uses: actions/download-artifact@v2
        with:
          name: node_modules
          path: ./Backend/node_modules

      - name: Run tests
        run: |
          cd ./Backend
          npm test

  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.CONTAINER_REPO_USERNAME }}
          password: ${{ secrets.CONTAINER_REPO_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./Backend
          file: ./Backend/Dockerfile
          push: true
          tags: vladina/tree-task-backend:latest
