name: frontend pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest # The type of runner that the job will run on
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21"
      - name: Install dependencies
        run: |
          cd ./Frontend
          npm install vite
      - name: Build the project
        run: |
          cd ./Frontend
          npm run build

    # - name: Archive production artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: frontend-build
    #     path: path/to/your/build/directory
  package:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.CONTAINER_REPO_USERNAME  }}
          password: ${{ secrets.CONTAINER_REPO_PASSWORD  }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./Frontend
          file: ./Frontend/Dockerfile
          push: true
          tags: vladina/tree-task-frontend:1.0.0